name: "Eureka Service Build"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  build:
     name: Maven Build
     runs-on: [ ubuntu-latest ]
     steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
